homeassistant:
  #  name: Hem
  #  latitude: !secret homeassistant_latitude
  #  longitude: !secret homeassistant_longitude
  #  elevation: !secret homeassistant_elevation
  #  unit_system: metric
  #  temperature_unit: C
  #  time_zone: Europe/Stockholm
  #  currency: SEK
  packages: !include_dir_named include
#  allowlist_external_dirs:
#    - /config

default_config:

automation: !include automations.yaml
frontend: !include themes.yaml

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/stack-in-card/stack-in-card.js
      type: module
    - url: /hacsfiles/decluttering-card/decluttering-card.js
      type: module
    - url: /hacsfiles/atomic-calendar-revive/atomic-calendar-revive.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
      type: module
    - url: /hacsfiles/lovelace-thermostat-dark-card/thermostat-dark-card.js
      type: module
    - url: /hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/bar-card/bar-card.js
      type: module
    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
      type: module
    - url: /hacsfiles/lovelace-home-feed-card/lovelace-home-feed-card.js
      type: module
    - url: /hacsfiles/weather-card/weather-card.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/Homekit-panel-card/homekit-panel-card.js
      type: module
    - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
      type: module
    - url: /hacsfiles/swipe-card/swipe-card.js
      type: module
    - url: /local/custom_icons.js?v=28082021
      type: module
    - url: /local/calendar-card.js?v=3.109.1
      type: module
    - url: /local/marked.min.js?v=4.0.12
      type: module
    - url: /local/vanilla-tilt.min.js?v=1.7.2
      type: module
    - url: /local/font.css
      type: css
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/light-popup-card/light-popup-card.js
      type: module
    - url: /hacsfiles/light-entity-card/light-entity-card.js
      type: module
    - url: /hacsfiles/kiosk-mode/kiosk-mode.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/apexcharts-card/apexcharts-card.js
      type: module
# Text to speech
tts:
  - platform: google_translate

ffmpeg:

wake_on_lan:

logger:
  default: warning
  logs:
    homeassistant.components.websocket_api: fatal
    homeassistant.components.camera: fatal
    homeassistant.helpers.entity: fatal

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: 83z4f8034zr893z48z74
  max_retries: 3
  default_measurement: state


pyscript:
  allow_all_imports: true
  hass_is_global: true

waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: !secret waste_collection_schedule_url


#google:
#  client_id: !secret google_client_id
#  client_secret: !secret google_client_secret

icloud:
  - username: !secret icloud_username
    password: !secret icloud_password
    with_family: true

calendar:
  - platform: caldav
    username: !secret caldav_username
    password: !secret caldav_password
    url: https://caldav.icloud.com

browser_mod:
  devices:
    e7e62cdb-f4309443:
      name: browser_tablet
  disable:
    - all

webostv:
  host: !secret webostv_host
  name: Living Room TV
  turn_on_action:
    service: scene.turn_on
    target:
      entity_id: scene.lg_fernseher_power

history:
  exclude:
    entities:
      - sensor.last_boot
      - sensor.date
      - sensor.date_time
      - sensor.date_time_iso
      - sensor.date_time_utc
      - sensor.internet_time
      - sensor.time_date
      - sensor.time_utc
      - sensor.time
      - input_text.ignore_motion



plant:
  aurora_2:
    sensors:
      moisture: sensor.flora_1_moisture
      battery: sensor.flora_1_battery
      temperature: sensor.flora_1_temperature
      conductivity: sensor.flora_1_conductivity
      brightness: sensor.flora_1_brightness
    min_moisture: 25
    max_moisture: 70
    min_conductivity: 0
    min_temperature: 10
    max_temperature: 30
  aurora_1:
    sensors:
      moisture: sensor.flora_2_moisture
      battery: sensor.flora_2_battery
      temperature: sensor.flora_2_temperature
      conductivity: sensor.flora_2_conductivity
      brightness: sensor.flora_2_brightness
    min_moisture: 25
    max_moisture: 70
    min_conductivity: 0
    min_temperature: 10
    max_temperature: 30

#timer:
#  laundry:
#    duration: 01:00:00
#    icon: mdi:washing-machine

#notify:
#  - name: ALL_DEVICES
#    platform: group
#    services:
#      - service: mobile_app_mattias_iphone_ios
#      - service: mobile_app_mattias_imac
#      - service: mobile_app_sanja_iphone

#monitor_docker:
#  - name: Docker
#    monitored_conditions: [allinone]
#    scan_interval: 120
#
#  - name: RPi Docker
#    url: !secret monitor_docker_rpi_url
#    monitored_conditions: [allinone]
#    scan_interval: 120
#
#lock:
#  - platform: template
#    name: Dator
#    value_template: >
#      {{ states('input_boolean.computer_lock') }}
#    lock:
#      service: input_boolean.turn_on
#      entity_id: input_boolean.computer_lock
#    unlock:
#      service: input_boolean.turn_off
#      entity_id: input_boolean.computer_lock
